export const DELITOS = [
    'abigeato',
    'aborto',
    'abuso de confianza',
    'abuso de firma en blanco',
    'abuso sexual',
    'agio',
    'agravación', 
    'allanamiento de domicilio o sus dependencias', 
    'alteración de linderos', 
    'alzamiento de bienes o falencia civil', 
    'amenazas', 
    'apropiación indebida', 
    'asesinato', 
    'asociación delictuosa', 
    'atentados contra la libertad de trabajo', 
    'bigamia', 
    'calumnia', 
    'cheque en descubierto', 
    'coacción', 
    'cohecho activo', 
    'cohecho pasivo propio', 
    'conducción peligrosa de vehículos', 
    'conducta culposa', 
    'contratos lesivos al estado', 
    'corrupción de menores', 
    'daño calificado', 
    'delitos contra la salud pública', 
    'desacato', 
    'desobediencia a la autoridad', 
    'despojo', 
    'difamación', 
    'ejercicio ilegal de la medicina', 
    'ejercicio indebido de profesión', 
    'encubrimiento', 
    'engaño a personas incapaces', 
    'engaño en productos industriales', 
    'estafa', 
    'estelionato', 
    'estupro',  
    'evasión de impuestos', 
    'excepción de verdad', 
    'extorsión', 
    'extradición', 
    'falsedad ideológica', 
    'falsedad material', 
    'falsificación de documento privado', 
    'falso testimonio', 
    'genocidio', 
    'giro defectuoso de cheque', 
    'homicidio', 
    'homicidio culposo', 
    'homicidio en riña o a consecuencia de agresión', 
    'homicidio por emoción violenta', 
    'hurto', 
    'incendio', 
    'incumplimiento de contratos', 
    'incumplimiento de deberes', 
    'injuria', 
    'instigación pública a delinquir', 
    'lesiones culposas', 
    'lesiones graves y leves', 
    'lesiones gravísimas', 
    'lesión seguida de muerte', 
    'malversación', 
    'nombramientos ilegales', 
    'omisión de denuncia', 
    'omisión de socorro', 
    'organización criminal', 
    'parricidio', 
    'peculado', 
    'peligro de estrago', 
    'perturbación de posesión', 
    'prevaricato', 
    'privación de libertad', 
    'propalación de ofensas', 
    'quiebra', 
    'receptación', 
    'resoluciones contrarias a la constitución y a las leyes', 
    'revelación de secretos', 
    'robo', 
    'robo agravado', 
    'sabotaje', 
    'secuestro', 
    'sedición', 
    'sociedades o asociaciones ficticias', 
    'supresión o destrucción de documento', 
    'terrorismo', 
    'traición', 
    'uso indebido de influencias', 
    'usura', 
    'usurpación', 
    'usurpación agravada', 
    'vejaciones y torturas', 
    'violación']